services:
  couchdb:
    container_name: couchdb
    hostname: couchdb.riodelaplata
    image: couchdb
    restart: unless-stopped
    ports:
        - 5984:5984
    volumes:
        - ./data:/opt/couchdb/data
        - ./etc:/opt/couchdb/etc/local.d
    environment:
        - COUCHDB_USER=${COUCHDB_USER}
        - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

networks:
  default:
    name: riodelaplata-net
    external: true
